port: 8080
jwt_secret_key: secret_key_jwt
log:
  level: "INFO"
  format: "JSON"
components:
  database:
      name: "blog"
      username: "postgres"
      password: "password"
      host: "127.0.0.1"
      port: "5432"
      connectionslimit: 10
      connectiontimeout: "3s"
      connectionlifetime: "5m"
  cache:
    host: "127.0.0.1"
    port: 6379
    cache_expiration: "10m"